# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 801, 631))
        self.label.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-20, 10, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 0, 461, 611))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/akhta/Desktop/cry baby.png"))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 490, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"background-color: rgb(228, 249, 255);\n"
"color: rgb(255, 90, 93);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.ShowSecond_window)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 191, 191))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def ShowSecond_window(self):
        print("Button Pressed")
        from desktop_app2 import Ui_MainWindow as popupScreen
        self.MainWindow2 = QtWidgets.QMainWindow()
        # MainWindow2.setFixedWidth(800)
        # MainWindow2.setFixedHeight(600)
        self.ui =popupScreen()
        self.ui.setupUi(self.MainWindow2)
        self.MainWindow2.show()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spider Man"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0004;\">Spider Man</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Press This"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#1d00ff;\">The Best lines</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#1d00ff;\"> from</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#1d00ff;\"> Spider Man Movie</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setFixedWidth(800)
    MainWindow.setFixedHeight(600)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
